### ISSUE TITLE
outputFile dropped in v0.3.4 - related to Jenkins CI integration

### ISSUE THREAD

**Issue by erkobridee** [karma-runner/karma-junit-reporter#58] opened 2015-08-29 16:00 UTC
Reading the Karma Runner v0.13 doc to integrate with [Jenkins CI](https://karma-runner.github.io/0.13/plus/jenkins.html), there indicates to use `outputFile`

But in the last version (0.3.4 [index.js](https://github.com/karma-runner/karma-junit-reporter/blob/v0.3.4/index.js)) I don't found this support in the code, until 0.3.3 in the [index.js was loaded in line 10](https://github.com/karma-runner/karma-junit-reporter/blob/v0.3.3/index.js#L10) and used inside  [writeXmlForBrowser function](https://github.com/karma-runner/karma-junit-reporter/blob/v0.3.3/index.js#L40-L48)

--

for now to generate report to Jenkins CI I'm using [v0.2.2](https://github.com/karma-runner/karma-junit-reporter/tree/v0.2.2) and [Jenkins CI config from Karma Runner v0.12](https://karma-runner.github.io/0.12/plus/jenkins.html)

```javascript
...
    // test results reporter to use
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['junit', 'coverage'],

    // https://karma-runner.github.io/0.12/plus/jenkins.html
    // https://github.com/karma-runner/karma-junit-reporter
    junitReporter: {
      outputFile: 'tests_out/junit/test-results.xml'
    },

    // https://github.com/karma-runner/karma-coverage
    // https://github.com/yahoo/istanbul

    // optionally, configure the reporter
    coverageReporter: {
      type : 'lcovonly', // produces an lcov.info file
      dir : 'tests_out/coverage/',
      subdir: '.'
    },
...
```

**Comment by tonyfinn** [comment] 2015-08-31 10:18
Yeah, the support for this seems to have been removed in 0.3.4: https://github.com/karma-runner/karma-junit-reporter/pull/36/files#diff-168726dbe96b3ce427e7fedce31bb0bcR40

(Also, even if you were only using outputDir, the format of the output file name changed, which caused us a surprise this morning)

It is still documented though, so should really either add it back or add a note that to the changelog that it is no longer supported.

**Comment by mathilde-pellerin** [comment] 2015-08-31 12:19
+1

**Comment by evandavis** [comment] 2015-09-02 16:02
+1

**Comment by leigh-mckenzie-pi** [comment] 2015-09-02 23:25
+1

**Comment by Dignifiedquire** [comment] 2015-09-03 20:10
Yes this was an oversight when I merged #36. This option should be added back in for sure. Very sorry about tha

**Comment by Dignifiedquire** [comment] 2015-09-03 20:38
Please checkout out #59 if that fixes the issue.

**Comment by erkobridee** [comment] 2015-09-03 22:04
hi @Dignifiedquire thanks

reading the new code, will fix partially... because of lines [44](https://github.com/karma-runner/karma-junit-reporter/blob/fix-output-file/index.js#L44) and [46](https://github.com/karma-runner/karma-junit-reporter/blob/fix-output-file/index.js#L46). Why we need output the browser name? :smiley: 

ps.: in v0.2.2 we can define all output path, so if I define the config:
```javascript
...
    // https://karma-runner.github.io/0.12/plus/jenkins.html
    // https://github.com/karma-runner/karma-junit-reporter/tree/v0.2.2
    junitReporter: {
      outputFile: 'tests_out/junit/test-results.xml'
    },
...
```

this will generate the exactly output in the config: `tests_out/junit/test-results.xml` 

but with the proposed change if I config:
```javascript
...
    // https://karma-runner.github.io/0.13/plus/jenkins.html
    // https://github.com/karma-runner/karma-junit-reporter/tree/fix-output-file
    junitReporter: {
      outputDir: 'tests_out/junit',
      outputFile: 'test-results.xml'
    },
...
```
and for example choose the PhantomJS browser to run tests, this will generate: `tests_out/junit/PHANTOMJS/test-results.xml`

**Comment by Dignifiedquire** [comment] 2015-09-03 22:12
@erkobridee the issue is that when there are multiple browsers we need a way to distinguish different test reports, and your config file does not know anything about that. So we need to either add the browser name as a directory or to the file name.

**Comment by erkobridee** [comment] 2015-09-03 22:28
@Dignifiedquire is it possible in somehow have one config to force this kind of output?

Thanks

**Comment by evandavis** [comment] 2015-09-04 13:12
@erkobridee agreed; it seems like anything after v0.2.2 breaks Jenkins integration because it won't know where to expect the file. I wonder if we need to fork junit-reporter into jenkins-reporter to restore this. (Actually I think someone has already [done that](https://github.com/actano/karma-jenkins-reporter)...)

**Comment by erkobridee** [comment] 2015-09-04 13:28
@evandavis @Dignifiedquire 

I'm thinking... we could do like in v0.2.2 where, if we define `outputFile ` this will define all output path and if we define only the `outputDir ` this should output report per browser 

well, that's my suggestion o/

What do you think? :smile:

**Comment by simonvanderveldt** [comment] 2015-09-04 13:53
@erkobridee That makes sense (just ran into this issue as well)
Does that mean that when setting `outputFile` different browser results will all be present in that single file?

**Comment by evandavis** [comment] 2015-09-04 14:16
@simonvanderveldt I think the problem is trying to satisfy two different use cases. On one hand, a jUnit style reporter should be able to generate reports for each browser. However, for Jenkins integration, we (likely) just need the results of a Phantom (or other headless) test where we expect the results to always be in the same place.

**Comment by erkobridee** [comment] 2015-09-04 14:26
@simonvanderveldt like @evandavis said, when we thinking and integrating with Jenkins CI we expect only 1 file to be read by Jenkins CI (in CI server normally we have one linux serve without UI and we put tests with karma to run only in PhantomJS, so we are running Unit Tests, I don't expect any weird behavior to execute javascript among each browser) :smile:

**Comment by simonvanderveldt** [comment] 2015-09-04 14:48
@erkobridee 
Wouldn't `tests_out/junit/TESTS-PhantomJS*.xml` in Jenkins together with `outputDir: tests_out/junit` in `karma.conf.js` work in that case?

**Comment by TheSavior** [comment] 2015-09-07 02:38
It looks like there were commits that fixed this issue, what is the status of this? We look forward to a patch release.

**Comment by Dignifiedquire** [comment] 2015-09-07 15:47
I can understand that you need a predefined location, but the reporter will not know this, and if there are multiple browser reports written and we do not distinguish them they will overwrite each other which is really not a desired behaviour. 

One thing that would be possible is to not nest the folders, but instead allow a template string, so you could write:

```js
outputFile: 'results-${browser}.xml'
// or if you want to risk overwriting
outputFile: 'results.xml'
```

But please first explore if the tip from @simonvanderveldt using a glob in Jenkins solves the issue.

**Comment by TheSavior** [comment] 2015-09-07 21:22
`suite` is option flag as well, perhaps the xml file should be prefixed with suite if suite is specified.

**Comment by erkobridee** [comment] 2015-09-08 03:30
@simonvanderveldt I test you suggestion and works fine :smile: 

well the actual "big" issue today is the [Jenkins CI integration doc on Karma Runner v0.13 page](https://karma-runner.github.io/0.13/plus/jenkins.html) is outdated...

so I write one little project to make some tests... and doc how to config Jenkins CI correctly

* [[GitHub] erkobridee / jenkins-ci-and-karma-junit-reporter](https://github.com/erkobridee/jenkins-ci-and-karma-junit-reporter) - Example to execute Karma Runner through Jenkinks CI and load xml report file
  
  * [releases](https://github.com/erkobridee/jenkins-ci-and-karma-junit-reporter/releases)

    * [v0.1.0](https://github.com/erkobridee/jenkins-ci-and-karma-junit-reporter/releases/tag/0.1.0) - karma-junit-reporter v0.2.2

      * on post-build action to load test report xmls : `tests_out/junit/*.xml`

    * [v0.2.0](https://github.com/erkobridee/jenkins-ci-and-karma-junit-reporter/releases/tag/0.2.0) - karma-junit-reporter v0.3.4

      * on post-build action to load test report xmls : `tests_out/junit/*.xml`

    * [v0.3.0-alpha](https://github.com/erkobridee/jenkins-ci-and-karma-junit-reporter/releases/tag/0.2.0) - karma-junit-reporter commit b4583b53563ea8e9e0a127705defcc8359c7635c related to [#59](https://github.com/karma-runner/karma-junit-reporter/pull/59)

      * on post-build action to load test report xmls : `tests_out/junit/**/*.xml`

one weird thing I saw...

loading xml generate from v0.2.2 show only one entry 
![tests_result_v0 2 2](https://cloud.githubusercontent.com/assets/342471/9725844/a955f928-55c0-11e5-91c6-63498c47aef5.png)

and load xml generate from v0.3.4 and the commit from #59 generate 2 entries
![tests_result_v0 3 4](https://cloud.githubusercontent.com/assets/342471/9725865/d5223634-55c0-11e5-8d93-8548c59d00e8.png)

**Comment by aindlq** [comment] 2015-09-11 16:29
@simonvanderveldt @Dignifiedquire 
I found the cause of duplication, see my comments for b4583b53563ea8e9e0a127705defcc8359c7635c

**Closed** 2015-09-27 17:39 UTC
Labels: discuss, type: bug
