### ISSUE TITLE
Report file always saves to project root as "test-results.xml"

### ISSUE THREAD

**Issue by zsiswick** [karma-runner/karma-junit-reporter#33] opened 2015-02-11 16:05 UTC
Following the example on the readme, when I edit this line: outputFile: 'reports/results.xml', it won't save the report in the reports folder, nor rename the file to "results.xml"

**Comment by busches** [comment] 2015-04-10 18:02
I'm not able to reproduce this, if I have
```
junitReporter: {
  outputFile: 'test-moo.xml'
},
```

It spits out a `test-moo.xml` file. Can you provide your exact configuration to reproduce?

**Comment by dmitry** [comment] 2015-04-25 15:30
Works for me with `junitReporter`. Looks like can be closed.

**Comment by dmkelly** [comment] 2015-07-08 19:57
I believe this is an issue with the documentation in the readme. I ran into this as well. The readme specifies using `outputDir` when it should be `outputFile`.

**Comment by janeklb** [comment] 2015-07-08 20:03
`outputFile` is the older configuration option - the new option (`outputDir`) is available in master, though I don't believe it's been released in a new version yet.

**Comment by Dignifiedquire** [comment] 2015-07-08 20:09
@janeklb yes you are right, haven't gotten around to finish my cleanup and pushing a release out yet

**Comment by janeklb** [comment] 2015-07-08 20:10
@Dignifiedquire waiting for it :) will you release this as 0.3.x since it's got an API change?

**Comment by busches** [comment] 2015-07-08 20:20
@janeklb since it's a breaking release, it should be a major version increase, not just feature.

**Comment by Dignifiedquire** [comment] 2015-07-08 20:36
@busches that only applies for versions `> 1.0.0`, so yes this will go out as `0.3.0`

**Comment by Dignifiedquire** [comment] 2015-07-08 20:42
And published as `0.3.0`

**Comment by busches** [comment] 2015-07-08 21:43
That's pretty confusing. What's stopping you from going 1.0, it works and it works well.

**Comment by Dignifiedquire** [comment] 2015-07-08 21:44
`1.0` release is in the works https://github.com/karma-runner/karma/issues/1406 but it takes some time, and I want to clean up things an bring everything in line before I do it

**Comment by Dignifiedquire** [comment] 2015-07-08 21:45
Closing as it seems the issue is resolved, please reopen if this is still a problem

**Closed by Dignifiedquire** 2015-07-08 21:45 UTC
